config/routes.rb
require_relative "../lib/constraints/marketing_constraint"
require_relative "../lib/constraints/organization_constraint"

Rails.application.routes.draw do
  root "static_pages#home"
  post "/graphql", to: "graphql#execute"

  # Do not allow routes with pattern "/1/*"
  constraints MarketingConstraint do
    devise_for :users, controllers: {
      registrations: "registrations",
      sessions: "sessions"
    }

    resources :organizations, only: %i[index new create], path: "orgs"
  end

  # Only allow routes that match the pattern "/1/*", where "1" is the organization id
  constraints OrganizationConstraint do
    scope module: :app do
      resources :dashboards, only: :index, path: "dashboard"
      resources :events, only: :create

      namespace :schedule do
        resources :months, only: :index, path: "month"
      end
    end
  end

  if Rails.env.development?
    mount Lookbook::Engine, at: "/lookbook"
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
end

app/views/layouts/application.html.haml
!!! 5
%html{lang: "en"}
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title Calendly
    %meta{content: "width=device-width,initial-scale=1", name: "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", data: {turbo_track: "reload"}
    = javascript_include_tag "application", data: {turbo_track: "reload"}, defer: true

  %body.min-h-screen.flex.bg-white.text-gray-900.text-sm.overflow-hidden
    %aside.flex-shrink-0.w-64.border-r.bg-gray-50
      .h-12.px-3.py-1
        %button{type: "button", class: "p-2 w-full flex items-center justify-between h-full bg-white rounded hover:bg-gray-200 focus:outline-none focus-visible:ring-inset focus-visible:ring-blue-500 focus-visible:ring-2", data: {test_id: "organization-switcher"}}
          %span.flex-1.flex.items-center.truncate.min-w-0
            %span.h-8.w-8.rounded.border.border-gray-300.inline-flex.items-center.justify-center.bg-white
              S
            %span.inline-block.ml-2.font-semibold.text-left.truncate
              Sidekick Therapy Partners
          %span.flex-shrink-0.ml-2.text-gray-500
            = heroicon "chevron-down", variant: :mini

      %div{class: "px-3 py-1 space-y-0.5"}
        = active_link_to dashboards_path, class: "flex items-center py-1.5 px-2 rounded hover:bg-gray-200 focus:outline-none focus-visible:ring-inset focus-visible:ring-blue-500 focus-visible:ring-2", active_class: "bg-gray-200 font-semibold" do
          %span.flex-shrink-0.text-gray-600
            = heroicon "home", size: 20
          %span.ml-2.flex-1
            Dashboard

        = active_link_to schedule_months_path, class: "flex items-center py-1.5 px-2 rounded hover:bg-gray-200 focus:outline-none focus-visible:ring-inset focus-visible:ring-blue-500 focus-visible:ring-2", active_class: "bg-gray-200 font-semibold" do
          %span.flex-shrink-0.text-gray-600
            = heroicon "calendar", size: 20
          %span.ml-2.flex-1
            Schedule

        %a{href: "#", class: "flex items-center py-1.5 px-2 rounded hover:bg-gray-200 focus:outline-none focus-visible:ring-inset focus-visible:ring-blue-500 focus-visible:ring-2"}
          %span.flex-shrink-0.text-gray-600
            = heroicon "user-group", size: 20
          %span.ml-2.flex-1
            Members

        %a{href: "#", class: "flex items-center py-1.5 px-2 rounded hover:bg-gray-200 focus:outline-none focus-visible:ring-inset focus-visible:ring-blue-500 focus-visible:ring-2"}
          %span.flex-shrink-0.text-gray-600
            = heroicon "users", size: 20
          %span.ml-2.flex-1
            Patients

        %a{href: "#", class: "flex items-center py-1.5 px-2 rounded hover:bg-gray-200 focus:outline-none focus-visible:ring-inset focus-visible:ring-blue-500 focus-visible:ring-2"}
          %span.flex-shrink-0.text-gray-600
            = heroicon "archive-box", size: 20
          %span.ml-2.flex-1
            Resources

        %a{href: "#", class: "flex items-center py-1.5 px-2 rounded hover:bg-gray-200 focus:outline-none focus-visible:ring-inset focus-visible:ring-blue-500 focus-visible:ring-2"}
          %span.flex-shrink-0.text-gray-600
            = heroicon "clipboard", size: 20
          %span.ml-2.flex-1
            Goals

        %a{href: "#", class: "flex items-center py-1.5 px-2 rounded hover:bg-gray-200 focus:outline-none focus-visible:ring-inset focus-visible:ring-blue-500 focus-visible:ring-2"}
          %span.flex-shrink-0.text-gray-600
            = heroicon "cog-6-tooth", size: 20
          %span.ml-2.flex-1
            Settings

    .flex-1.flex.flex-col
      = render(NavbarComponent.new(current_user: current_user))

      %div{class: class_names("flex-1 flex flex-col", "px-4": !active_link?(schedule_months_path))}
        = yield

app/views/layouts/marketing.html.haml
!!! 5
%html{lang: "en"}
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title Calendly
    %meta{content: "width=device-width,initial-scale=1", name: "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", data: {turbo_track: "reload"}
    = javascript_include_tag "application", data: {turbo_track: "reload"}, defer: true

  %body
    = yield

app/views/layouts/slate.html.haml
!!! 5
%html{lang: "en"}
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title Calendly
    %meta{content: "width=device-width,initial-scale=1", name: "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", data: {turbo_track: "reload"}
    = javascript_include_tag "application", data: {turbo_track: "reload"}, defer: true

  %body.min-h-screen.flex.flex-col.bg-white.text-sm.text-gray-900
    - flash.each do |type, msg|
      = render(BannerComponent.new(variant: type.to_sym, full: true)) { msg }

    .flex-1.flex.flex-col.align-center.justify-center
      .max-w-sm.w-full.mx-auto.px-4
        = yield